fragment HeroParts on Hero {
  __typename
  badge
  headline
  subheading
  availabilityNotice
  instagramUrl
}

fragment EventsParts on Events {
  __typename
  title
  description
}

fragment ServicesParts on Services {
  __typename
  servicesList {
    __typename
    id
    name
    price
    duration
    description
    deliverables
    calSlug
  }
}

fragment PortfolioParts on Portfolio {
  __typename
  portfolioList {
    __typename
    id
    image
    alt
    tag
  }
}

fragment SiteParts on Site {
  __typename
  studioName
  stylistName
  title
  description
  email
  phone
  instagram
  locationDisplay
  priceRange
}
