//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  import type { TinaMarkdownContent } from 'tinacms/dist/rich-text';
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
  /** A rich-text document, renderable by TinaMarkdown */
  RichText: { input: TinaMarkdownContent; output: TinaMarkdownContent; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  site: Site;
  siteConnection: SiteConnection;
  hero: Hero;
  heroConnection: HeroConnection;
  portfolio: Portfolio;
  portfolioConnection: PortfolioConnection;
  services: Services;
  servicesConnection: ServicesConnection;
  events: Events;
  eventsConnection: EventsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteFilter>;
};


export type QueryHeroArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHeroConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HeroFilter>;
};


export type QueryPortfolioArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPortfolioConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PortfolioFilter>;
};


export type QueryServicesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServicesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServicesFilter>;
};


export type QueryEventsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEventsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EventsFilter>;
};

export type DocumentFilter = {
  site?: InputMaybe<SiteFilter>;
  hero?: InputMaybe<HeroFilter>;
  portfolio?: InputMaybe<PortfolioFilter>;
  services?: InputMaybe<ServicesFilter>;
  events?: InputMaybe<EventsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Site | Hero | Portfolio | Services | Events | Folder;

export type SiteAddress = {
  __typename?: 'SiteAddress';
  locality?: Maybe<Scalars['String']['output']>;
  region?: Maybe<Scalars['String']['output']>;
  country?: Maybe<Scalars['String']['output']>;
};

export type SiteGeo = {
  __typename?: 'SiteGeo';
  latitude?: Maybe<Scalars['Float']['output']>;
  longitude?: Maybe<Scalars['Float']['output']>;
};

export type Site = Node & Document & {
  __typename?: 'Site';
  studioName: Scalars['String']['output'];
  stylistName: Scalars['String']['output'];
  browserTitle?: Maybe<Scalars['String']['output']>;
  metaDescription?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  instagramHandle?: Maybe<Scalars['String']['output']>;
  locationDisplay?: Maybe<Scalars['String']['output']>;
  availabilityBanner?: Maybe<Scalars['String']['output']>;
  calUsername?: Maybe<Scalars['String']['output']>;
  calDefaultSlug?: Maybe<Scalars['String']['output']>;
  priceRange?: Maybe<Scalars['String']['output']>;
  address?: Maybe<SiteAddress>;
  geo?: Maybe<SiteGeo>;
  areaServed?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  keywords?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SiteAddressFilter = {
  locality?: InputMaybe<StringFilter>;
  region?: InputMaybe<StringFilter>;
  country?: InputMaybe<StringFilter>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type SiteGeoFilter = {
  latitude?: InputMaybe<NumberFilter>;
  longitude?: InputMaybe<NumberFilter>;
};

export type SiteFilter = {
  studioName?: InputMaybe<StringFilter>;
  stylistName?: InputMaybe<StringFilter>;
  browserTitle?: InputMaybe<StringFilter>;
  metaDescription?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  instagramHandle?: InputMaybe<StringFilter>;
  locationDisplay?: InputMaybe<StringFilter>;
  availabilityBanner?: InputMaybe<StringFilter>;
  calUsername?: InputMaybe<StringFilter>;
  calDefaultSlug?: InputMaybe<StringFilter>;
  priceRange?: InputMaybe<StringFilter>;
  address?: InputMaybe<SiteAddressFilter>;
  geo?: InputMaybe<SiteGeoFilter>;
  areaServed?: InputMaybe<StringFilter>;
  keywords?: InputMaybe<StringFilter>;
};

export type SiteConnectionEdges = {
  __typename?: 'SiteConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Site>;
};

export type SiteConnection = Connection & {
  __typename?: 'SiteConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteConnectionEdges>>>;
};

export type Hero = Node & Document & {
  __typename?: 'Hero';
  badge?: Maybe<Scalars['String']['output']>;
  headline: Scalars['String']['output'];
  subheading?: Maybe<Scalars['String']['output']>;
  availabilityNotice: Scalars['String']['output'];
  calSlug?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HeroFilter = {
  badge?: InputMaybe<StringFilter>;
  headline?: InputMaybe<StringFilter>;
  subheading?: InputMaybe<StringFilter>;
  availabilityNotice?: InputMaybe<StringFilter>;
  calSlug?: InputMaybe<StringFilter>;
};

export type HeroConnectionEdges = {
  __typename?: 'HeroConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Hero>;
};

export type HeroConnection = Connection & {
  __typename?: 'HeroConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HeroConnectionEdges>>>;
};

export type PortfolioPortfolioList = {
  __typename?: 'PortfolioPortfolioList';
  id: Scalars['String']['output'];
  image: Scalars['String']['output'];
  alt: Scalars['String']['output'];
  tag?: Maybe<Scalars['String']['output']>;
};

export type Portfolio = Node & Document & {
  __typename?: 'Portfolio';
  portfolioList?: Maybe<Array<Maybe<PortfolioPortfolioList>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PortfolioPortfolioListFilter = {
  id?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  tag?: InputMaybe<StringFilter>;
};

export type PortfolioFilter = {
  portfolioList?: InputMaybe<PortfolioPortfolioListFilter>;
};

export type PortfolioConnectionEdges = {
  __typename?: 'PortfolioConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Portfolio>;
};

export type PortfolioConnection = Connection & {
  __typename?: 'PortfolioConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PortfolioConnectionEdges>>>;
};

export type ServicesServicesList = {
  __typename?: 'ServicesServicesList';
  id: Scalars['String']['output'];
  name: Scalars['String']['output'];
  price: Scalars['String']['output'];
  duration: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  deliverables?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  calSlug?: Maybe<Scalars['String']['output']>;
};

export type Services = Node & Document & {
  __typename?: 'Services';
  sectionTitle?: Maybe<Scalars['String']['output']>;
  servicesList?: Maybe<Array<Maybe<ServicesServicesList>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ServicesServicesListFilter = {
  id?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  duration?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  deliverables?: InputMaybe<StringFilter>;
  calSlug?: InputMaybe<StringFilter>;
};

export type ServicesFilter = {
  sectionTitle?: InputMaybe<StringFilter>;
  servicesList?: InputMaybe<ServicesServicesListFilter>;
};

export type ServicesConnectionEdges = {
  __typename?: 'ServicesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Services>;
};

export type ServicesConnection = Connection & {
  __typename?: 'ServicesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ServicesConnectionEdges>>>;
};

export type EventsFormFieldsInputField = {
  __typename?: 'EventsFormFieldsInputField';
  label: Scalars['String']['output'];
  fieldType?: Maybe<Scalars['String']['output']>;
  placeholder?: Maybe<Scalars['String']['output']>;
  required?: Maybe<Scalars['Boolean']['output']>;
};

export type EventsFormFieldsSelectField = {
  __typename?: 'EventsFormFieldsSelectField';
  label: Scalars['String']['output'];
  options?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  required?: Maybe<Scalars['Boolean']['output']>;
};

export type EventsFormFieldsTextareaField = {
  __typename?: 'EventsFormFieldsTextareaField';
  label: Scalars['String']['output'];
  placeholder?: Maybe<Scalars['String']['output']>;
  required?: Maybe<Scalars['Boolean']['output']>;
};

export type EventsFormFields = EventsFormFieldsInputField | EventsFormFieldsSelectField | EventsFormFieldsTextareaField;

export type EventsFormOptions = {
  __typename?: 'EventsFormOptions';
  submitButtonText?: Maybe<Scalars['String']['output']>;
};

export type Events = Node & Document & {
  __typename?: 'Events';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  showForm?: Maybe<Scalars['Boolean']['output']>;
  formFields?: Maybe<Array<Maybe<EventsFormFields>>>;
  formOptions?: Maybe<EventsFormOptions>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type EventsFormFieldsInputFieldFilter = {
  label?: InputMaybe<StringFilter>;
  fieldType?: InputMaybe<StringFilter>;
  placeholder?: InputMaybe<StringFilter>;
  required?: InputMaybe<BooleanFilter>;
};

export type EventsFormFieldsSelectFieldFilter = {
  label?: InputMaybe<StringFilter>;
  options?: InputMaybe<StringFilter>;
  required?: InputMaybe<BooleanFilter>;
};

export type EventsFormFieldsTextareaFieldFilter = {
  label?: InputMaybe<StringFilter>;
  placeholder?: InputMaybe<StringFilter>;
  required?: InputMaybe<BooleanFilter>;
};

export type EventsFormFieldsFilter = {
  inputField?: InputMaybe<EventsFormFieldsInputFieldFilter>;
  selectField?: InputMaybe<EventsFormFieldsSelectFieldFilter>;
  textareaField?: InputMaybe<EventsFormFieldsTextareaFieldFilter>;
};

export type EventsFormOptionsFilter = {
  submitButtonText?: InputMaybe<StringFilter>;
};

export type EventsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  showForm?: InputMaybe<BooleanFilter>;
  formFields?: InputMaybe<EventsFormFieldsFilter>;
  formOptions?: InputMaybe<EventsFormOptionsFilter>;
};

export type EventsConnectionEdges = {
  __typename?: 'EventsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Events>;
};

export type EventsConnection = Connection & {
  __typename?: 'EventsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<EventsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateSite: Site;
  createSite: Site;
  updateHero: Hero;
  createHero: Hero;
  updatePortfolio: Portfolio;
  createPortfolio: Portfolio;
  updateServices: Services;
  createServices: Services;
  updateEvents: Events;
  createEvents: Events;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteMutation;
};


export type MutationCreateSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteMutation;
};


export type MutationUpdateHeroArgs = {
  relativePath: Scalars['String']['input'];
  params: HeroMutation;
};


export type MutationCreateHeroArgs = {
  relativePath: Scalars['String']['input'];
  params: HeroMutation;
};


export type MutationUpdatePortfolioArgs = {
  relativePath: Scalars['String']['input'];
  params: PortfolioMutation;
};


export type MutationCreatePortfolioArgs = {
  relativePath: Scalars['String']['input'];
  params: PortfolioMutation;
};


export type MutationUpdateServicesArgs = {
  relativePath: Scalars['String']['input'];
  params: ServicesMutation;
};


export type MutationCreateServicesArgs = {
  relativePath: Scalars['String']['input'];
  params: ServicesMutation;
};


export type MutationUpdateEventsArgs = {
  relativePath: Scalars['String']['input'];
  params: EventsMutation;
};


export type MutationCreateEventsArgs = {
  relativePath: Scalars['String']['input'];
  params: EventsMutation;
};

export type DocumentUpdateMutation = {
  site?: InputMaybe<SiteMutation>;
  hero?: InputMaybe<HeroMutation>;
  portfolio?: InputMaybe<PortfolioMutation>;
  services?: InputMaybe<ServicesMutation>;
  events?: InputMaybe<EventsMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  site?: InputMaybe<SiteMutation>;
  hero?: InputMaybe<HeroMutation>;
  portfolio?: InputMaybe<PortfolioMutation>;
  services?: InputMaybe<ServicesMutation>;
  events?: InputMaybe<EventsMutation>;
};

export type SiteAddressMutation = {
  locality?: InputMaybe<Scalars['String']['input']>;
  region?: InputMaybe<Scalars['String']['input']>;
  country?: InputMaybe<Scalars['String']['input']>;
};

export type SiteGeoMutation = {
  latitude?: InputMaybe<Scalars['Float']['input']>;
  longitude?: InputMaybe<Scalars['Float']['input']>;
};

export type SiteMutation = {
  studioName?: InputMaybe<Scalars['String']['input']>;
  stylistName?: InputMaybe<Scalars['String']['input']>;
  browserTitle?: InputMaybe<Scalars['String']['input']>;
  metaDescription?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  instagramHandle?: InputMaybe<Scalars['String']['input']>;
  locationDisplay?: InputMaybe<Scalars['String']['input']>;
  availabilityBanner?: InputMaybe<Scalars['String']['input']>;
  calUsername?: InputMaybe<Scalars['String']['input']>;
  calDefaultSlug?: InputMaybe<Scalars['String']['input']>;
  priceRange?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<SiteAddressMutation>;
  geo?: InputMaybe<SiteGeoMutation>;
  areaServed?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  keywords?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HeroMutation = {
  badge?: InputMaybe<Scalars['String']['input']>;
  headline?: InputMaybe<Scalars['String']['input']>;
  subheading?: InputMaybe<Scalars['String']['input']>;
  availabilityNotice?: InputMaybe<Scalars['String']['input']>;
  calSlug?: InputMaybe<Scalars['String']['input']>;
};

export type PortfolioPortfolioListMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
  tag?: InputMaybe<Scalars['String']['input']>;
};

export type PortfolioMutation = {
  portfolioList?: InputMaybe<Array<InputMaybe<PortfolioPortfolioListMutation>>>;
};

export type ServicesServicesListMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  duration?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  deliverables?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  calSlug?: InputMaybe<Scalars['String']['input']>;
};

export type ServicesMutation = {
  sectionTitle?: InputMaybe<Scalars['String']['input']>;
  servicesList?: InputMaybe<Array<InputMaybe<ServicesServicesListMutation>>>;
};

export type EventsFormFieldsInputFieldMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  fieldType?: InputMaybe<Scalars['String']['input']>;
  placeholder?: InputMaybe<Scalars['String']['input']>;
  required?: InputMaybe<Scalars['Boolean']['input']>;
};

export type EventsFormFieldsSelectFieldMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  options?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  required?: InputMaybe<Scalars['Boolean']['input']>;
};

export type EventsFormFieldsTextareaFieldMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  placeholder?: InputMaybe<Scalars['String']['input']>;
  required?: InputMaybe<Scalars['Boolean']['input']>;
};

export type EventsFormFieldsMutation = {
  inputField?: InputMaybe<EventsFormFieldsInputFieldMutation>;
  selectField?: InputMaybe<EventsFormFieldsSelectFieldMutation>;
  textareaField?: InputMaybe<EventsFormFieldsTextareaFieldMutation>;
};

export type EventsFormOptionsMutation = {
  submitButtonText?: InputMaybe<Scalars['String']['input']>;
};

export type EventsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  showForm?: InputMaybe<Scalars['Boolean']['input']>;
  formFields?: InputMaybe<Array<InputMaybe<EventsFormFieldsMutation>>>;
  formOptions?: InputMaybe<EventsFormOptionsMutation>;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type SiteAddressFilter = {
  locality?: StringFilter | null | undefined;
  region?: StringFilter | null | undefined;
  country?: StringFilter | null | undefined;
};

export type NumberFilter = {
  lt?: number | null | undefined;
  lte?: number | null | undefined;
  gte?: number | null | undefined;
  gt?: number | null | undefined;
  eq?: number | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<number | null | undefined> | null | undefined;
};

export type SiteGeoFilter = {
  latitude?: NumberFilter | null | undefined;
  longitude?: NumberFilter | null | undefined;
};

export type SiteFilter = {
  studioName?: StringFilter | null | undefined;
  stylistName?: StringFilter | null | undefined;
  browserTitle?: StringFilter | null | undefined;
  metaDescription?: StringFilter | null | undefined;
  email?: StringFilter | null | undefined;
  phone?: StringFilter | null | undefined;
  instagramHandle?: StringFilter | null | undefined;
  locationDisplay?: StringFilter | null | undefined;
  availabilityBanner?: StringFilter | null | undefined;
  calUsername?: StringFilter | null | undefined;
  calDefaultSlug?: StringFilter | null | undefined;
  priceRange?: StringFilter | null | undefined;
  address?: SiteAddressFilter | null | undefined;
  geo?: SiteGeoFilter | null | undefined;
  areaServed?: StringFilter | null | undefined;
  keywords?: StringFilter | null | undefined;
};

export type HeroFilter = {
  badge?: StringFilter | null | undefined;
  headline?: StringFilter | null | undefined;
  subheading?: StringFilter | null | undefined;
  availabilityNotice?: StringFilter | null | undefined;
  calSlug?: StringFilter | null | undefined;
};

export type ImageFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type PortfolioPortfolioListFilter = {
  id?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
  alt?: StringFilter | null | undefined;
  tag?: StringFilter | null | undefined;
};

export type PortfolioFilter = {
  portfolioList?: PortfolioPortfolioListFilter | null | undefined;
};

export type ServicesServicesListFilter = {
  id?: StringFilter | null | undefined;
  name?: StringFilter | null | undefined;
  price?: StringFilter | null | undefined;
  duration?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  deliverables?: StringFilter | null | undefined;
  calSlug?: StringFilter | null | undefined;
};

export type ServicesFilter = {
  sectionTitle?: StringFilter | null | undefined;
  servicesList?: ServicesServicesListFilter | null | undefined;
};

export type BooleanFilter = {
  eq?: boolean | null | undefined;
  exists?: boolean | null | undefined;
};

export type EventsFormFieldsInputFieldFilter = {
  label?: StringFilter | null | undefined;
  fieldType?: StringFilter | null | undefined;
  placeholder?: StringFilter | null | undefined;
  required?: BooleanFilter | null | undefined;
};

export type EventsFormFieldsSelectFieldFilter = {
  label?: StringFilter | null | undefined;
  options?: StringFilter | null | undefined;
  required?: BooleanFilter | null | undefined;
};

export type EventsFormFieldsTextareaFieldFilter = {
  label?: StringFilter | null | undefined;
  placeholder?: StringFilter | null | undefined;
  required?: BooleanFilter | null | undefined;
};

export type EventsFormFieldsFilter = {
  inputField?: EventsFormFieldsInputFieldFilter | null | undefined;
  selectField?: EventsFormFieldsSelectFieldFilter | null | undefined;
  textareaField?: EventsFormFieldsTextareaFieldFilter | null | undefined;
};

export type EventsFormOptionsFilter = {
  submitButtonText?: StringFilter | null | undefined;
};

export type EventsFilter = {
  title?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  showForm?: BooleanFilter | null | undefined;
  formFields?: EventsFormFieldsFilter | null | undefined;
  formOptions?: EventsFormOptionsFilter | null | undefined;
};

export type SitePartsFragment = { __typename: 'Site', studioName: string, stylistName: string, browserTitle: string | null, metaDescription: string | null, email: string | null, phone: string | null, instagramHandle: string | null, locationDisplay: string | null, availabilityBanner: string | null, calUsername: string | null, calDefaultSlug: string | null, priceRange: string | null, areaServed: Array<string | null> | null, keywords: Array<string | null> | null, address: { __typename: 'SiteAddress', locality: string | null, region: string | null, country: string | null } | null, geo: { __typename: 'SiteGeo', latitude: number | null, longitude: number | null } | null };

export type HeroPartsFragment = { __typename: 'Hero', badge: string | null, headline: string, subheading: string | null, availabilityNotice: string, calSlug: string | null };

export type PortfolioPartsFragment = { __typename: 'Portfolio', portfolioList: Array<{ __typename: 'PortfolioPortfolioList', id: string, image: string, alt: string, tag: string | null } | null> | null };

export type ServicesPartsFragment = { __typename: 'Services', sectionTitle: string | null, servicesList: Array<{ __typename: 'ServicesServicesList', id: string, name: string, price: string, duration: string, description: string | null, deliverables: Array<string | null> | null, calSlug: string | null } | null> | null };

export type EventsPartsFragment = { __typename: 'Events', title: string | null, description: string | null, showForm: boolean | null, formFields: Array<
    | { __typename: 'EventsFormFieldsInputField', label: string, fieldType: string | null, placeholder: string | null, required: boolean | null }
    | { __typename: 'EventsFormFieldsSelectField', label: string, options: Array<string | null> | null, required: boolean | null }
    | { __typename: 'EventsFormFieldsTextareaField', label: string, placeholder: string | null, required: boolean | null }
   | null> | null, formOptions: { __typename: 'EventsFormOptions', submitButtonText: string | null } | null };

export type SiteQueryVariables = Exact<{
  relativePath: string;
}>;


export type SiteQuery = { site: { __typename: 'Site', id: string, studioName: string, stylistName: string, browserTitle: string | null, metaDescription: string | null, email: string | null, phone: string | null, instagramHandle: string | null, locationDisplay: string | null, availabilityBanner: string | null, calUsername: string | null, calDefaultSlug: string | null, priceRange: string | null, areaServed: Array<string | null> | null, keywords: Array<string | null> | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, address: { __typename: 'SiteAddress', locality: string | null, region: string | null, country: string | null } | null, geo: { __typename: 'SiteGeo', latitude: number | null, longitude: number | null } | null } };

export type SiteConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: SiteFilter | null | undefined;
}>;


export type SiteConnectionQuery = { siteConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Site', id: string, studioName: string, stylistName: string, browserTitle: string | null, metaDescription: string | null, email: string | null, phone: string | null, instagramHandle: string | null, locationDisplay: string | null, availabilityBanner: string | null, calUsername: string | null, calDefaultSlug: string | null, priceRange: string | null, areaServed: Array<string | null> | null, keywords: Array<string | null> | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, address: { __typename: 'SiteAddress', locality: string | null, region: string | null, country: string | null } | null, geo: { __typename: 'SiteGeo', latitude: number | null, longitude: number | null } | null } | null } | null> | null } };

export type HeroQueryVariables = Exact<{
  relativePath: string;
}>;


export type HeroQuery = { hero: { __typename: 'Hero', id: string, badge: string | null, headline: string, subheading: string | null, availabilityNotice: string, calSlug: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type HeroConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: HeroFilter | null | undefined;
}>;


export type HeroConnectionQuery = { heroConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Hero', id: string, badge: string | null, headline: string, subheading: string | null, availabilityNotice: string, calSlug: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PortfolioQueryVariables = Exact<{
  relativePath: string;
}>;


export type PortfolioQuery = { portfolio: { __typename: 'Portfolio', id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, portfolioList: Array<{ __typename: 'PortfolioPortfolioList', id: string, image: string, alt: string, tag: string | null } | null> | null } };

export type PortfolioConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: PortfolioFilter | null | undefined;
}>;


export type PortfolioConnectionQuery = { portfolioConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Portfolio', id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, portfolioList: Array<{ __typename: 'PortfolioPortfolioList', id: string, image: string, alt: string, tag: string | null } | null> | null } | null } | null> | null } };

export type ServicesQueryVariables = Exact<{
  relativePath: string;
}>;


export type ServicesQuery = { services: { __typename: 'Services', id: string, sectionTitle: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, servicesList: Array<{ __typename: 'ServicesServicesList', id: string, name: string, price: string, duration: string, description: string | null, deliverables: Array<string | null> | null, calSlug: string | null } | null> | null } };

export type ServicesConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: ServicesFilter | null | undefined;
}>;


export type ServicesConnectionQuery = { servicesConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Services', id: string, sectionTitle: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, servicesList: Array<{ __typename: 'ServicesServicesList', id: string, name: string, price: string, duration: string, description: string | null, deliverables: Array<string | null> | null, calSlug: string | null } | null> | null } | null } | null> | null } };

export type EventsQueryVariables = Exact<{
  relativePath: string;
}>;


export type EventsQuery = { events: { __typename: 'Events', id: string, title: string | null, description: string | null, showForm: boolean | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, formFields: Array<
      | { __typename: 'EventsFormFieldsInputField', label: string, fieldType: string | null, placeholder: string | null, required: boolean | null }
      | { __typename: 'EventsFormFieldsSelectField', label: string, options: Array<string | null> | null, required: boolean | null }
      | { __typename: 'EventsFormFieldsTextareaField', label: string, placeholder: string | null, required: boolean | null }
     | null> | null, formOptions: { __typename: 'EventsFormOptions', submitButtonText: string | null } | null } };

export type EventsConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: EventsFilter | null | undefined;
}>;


export type EventsConnectionQuery = { eventsConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Events', id: string, title: string | null, description: string | null, showForm: boolean | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, formFields: Array<
          | { __typename: 'EventsFormFieldsInputField', label: string, fieldType: string | null, placeholder: string | null, required: boolean | null }
          | { __typename: 'EventsFormFieldsSelectField', label: string, options: Array<string | null> | null, required: boolean | null }
          | { __typename: 'EventsFormFieldsTextareaField', label: string, placeholder: string | null, required: boolean | null }
         | null> | null, formOptions: { __typename: 'EventsFormOptions', submitButtonText: string | null } | null } | null } | null> | null } };

export const SitePartsFragmentDoc = gql`
    fragment SiteParts on Site {
  __typename
  studioName
  stylistName
  browserTitle
  metaDescription
  email
  phone
  instagramHandle
  locationDisplay
  availabilityBanner
  calUsername
  calDefaultSlug
  priceRange
  address {
    __typename
    locality
    region
    country
  }
  geo {
    __typename
    latitude
    longitude
  }
  areaServed
  keywords
}
    `;
export const HeroPartsFragmentDoc = gql`
    fragment HeroParts on Hero {
  __typename
  badge
  headline
  subheading
  availabilityNotice
  calSlug
}
    `;
export const PortfolioPartsFragmentDoc = gql`
    fragment PortfolioParts on Portfolio {
  __typename
  portfolioList {
    __typename
    id
    image
    alt
    tag
  }
}
    `;
export const ServicesPartsFragmentDoc = gql`
    fragment ServicesParts on Services {
  __typename
  sectionTitle
  servicesList {
    __typename
    id
    name
    price
    duration
    description
    deliverables
    calSlug
  }
}
    `;
export const EventsPartsFragmentDoc = gql`
    fragment EventsParts on Events {
  __typename
  title
  description
  showForm
  formFields {
    __typename
    ... on EventsFormFieldsInputField {
      label
      fieldType
      placeholder
      required
    }
    ... on EventsFormFieldsSelectField {
      label
      options
      required
    }
    ... on EventsFormFieldsTextareaField {
      label
      placeholder
      required
    }
  }
  formOptions {
    __typename
    submitButtonText
  }
}
    `;
export const SiteDocument = gql`
    query site($relativePath: String!) {
  site(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteParts
  }
}
    ${SitePartsFragmentDoc}`;
export const SiteConnectionDocument = gql`
    query siteConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteFilter) {
  siteConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteParts
      }
    }
  }
}
    ${SitePartsFragmentDoc}`;
export const HeroDocument = gql`
    query hero($relativePath: String!) {
  hero(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HeroParts
  }
}
    ${HeroPartsFragmentDoc}`;
export const HeroConnectionDocument = gql`
    query heroConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HeroFilter) {
  heroConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HeroParts
      }
    }
  }
}
    ${HeroPartsFragmentDoc}`;
export const PortfolioDocument = gql`
    query portfolio($relativePath: String!) {
  portfolio(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PortfolioParts
  }
}
    ${PortfolioPartsFragmentDoc}`;
export const PortfolioConnectionDocument = gql`
    query portfolioConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PortfolioFilter) {
  portfolioConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PortfolioParts
      }
    }
  }
}
    ${PortfolioPartsFragmentDoc}`;
export const ServicesDocument = gql`
    query services($relativePath: String!) {
  services(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ServicesParts
  }
}
    ${ServicesPartsFragmentDoc}`;
export const ServicesConnectionDocument = gql`
    query servicesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ServicesFilter) {
  servicesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ServicesParts
      }
    }
  }
}
    ${ServicesPartsFragmentDoc}`;
export const EventsDocument = gql`
    query events($relativePath: String!) {
  events(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...EventsParts
  }
}
    ${EventsPartsFragmentDoc}`;
export const EventsConnectionDocument = gql`
    query eventsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: EventsFilter) {
  eventsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EventsParts
      }
    }
  }
}
    ${EventsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      site(variables: SiteQueryVariables, options?: C): Promise<{data: SiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteQueryVariables, query: string}> {
        return requester<{data: SiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteQueryVariables, query: string}, SiteQueryVariables>(SiteDocument, variables, options);
      },
    siteConnection(variables?: SiteConnectionQueryVariables, options?: C): Promise<{data: SiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConnectionQueryVariables, query: string}> {
        return requester<{data: SiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConnectionQueryVariables, query: string}, SiteConnectionQueryVariables>(SiteConnectionDocument, variables, options);
      },
    hero(variables: HeroQueryVariables, options?: C): Promise<{data: HeroQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroQueryVariables, query: string}> {
        return requester<{data: HeroQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroQueryVariables, query: string}, HeroQueryVariables>(HeroDocument, variables, options);
      },
    heroConnection(variables?: HeroConnectionQueryVariables, options?: C): Promise<{data: HeroConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroConnectionQueryVariables, query: string}> {
        return requester<{data: HeroConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroConnectionQueryVariables, query: string}, HeroConnectionQueryVariables>(HeroConnectionDocument, variables, options);
      },
    portfolio(variables: PortfolioQueryVariables, options?: C): Promise<{data: PortfolioQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioQueryVariables, query: string}> {
        return requester<{data: PortfolioQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioQueryVariables, query: string}, PortfolioQueryVariables>(PortfolioDocument, variables, options);
      },
    portfolioConnection(variables?: PortfolioConnectionQueryVariables, options?: C): Promise<{data: PortfolioConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioConnectionQueryVariables, query: string}> {
        return requester<{data: PortfolioConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioConnectionQueryVariables, query: string}, PortfolioConnectionQueryVariables>(PortfolioConnectionDocument, variables, options);
      },
    services(variables: ServicesQueryVariables, options?: C): Promise<{data: ServicesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesQueryVariables, query: string}> {
        return requester<{data: ServicesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesQueryVariables, query: string}, ServicesQueryVariables>(ServicesDocument, variables, options);
      },
    servicesConnection(variables?: ServicesConnectionQueryVariables, options?: C): Promise<{data: ServicesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesConnectionQueryVariables, query: string}> {
        return requester<{data: ServicesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesConnectionQueryVariables, query: string}, ServicesConnectionQueryVariables>(ServicesConnectionDocument, variables, options);
      },
    events(variables: EventsQueryVariables, options?: C): Promise<{data: EventsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsQueryVariables, query: string}> {
        return requester<{data: EventsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsQueryVariables, query: string}, EventsQueryVariables>(EventsDocument, variables, options);
      },
    eventsConnection(variables?: EventsConnectionQueryVariables, options?: C): Promise<{data: EventsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsConnectionQueryVariables, query: string}> {
        return requester<{data: EventsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsConnectionQueryVariables, query: string}, EventsConnectionQueryVariables>(EventsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/3.0/content/87e12abe-90fc-43a9-9f88-48270c37724d/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  